name: "Release Notes"
description: "Retrieves release notes for a new release"
inputs:
  latest-release-tag:
    description: "The tag for the currently deployed release on production."
    required: true
  release-candidate-tag:
    description: "The tag for the release candidate going out to production"
    required: true
outputs:
  notes:
    description: "The formated release notes comprised of the commit messages"
runs:
  using: "node20"
  main: "dist/index.js"
